In [2]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n ",series)

Series
  0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
# Dataframe
import numpy as np
data = {
    'Name' : ['Pratham', 'Bob', 'Adi'],
    'Age' : [22,23,29],
    'city' : ['Mh', 'Bng', 'Delhi']
}
df = pd.DataFrame(data)
print(df)
np.array(df)

      Name  Age   city
0  Pratham   22     Mh
1      Bob   23    Bng
2      Adi   29  Delhi

array([['Pratham', 22, 'Mh'],
       ['Bob', 23, 'Bng'],
       ['Adi', 29, 'Delhi']], dtype=object)

In [4]:
import pandas as pd
df = pd.read_csv('Sale_data.csv')
df.head(12)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card
10,10011,2024-01-11,Beauty Products,Chanel No. 5 Perfume,1,129.99,129.99,Europe,PayPal
11,10012,2024-01-12,Sports,Babolat Pure Drive Tennis Racket,3,199.99,599.97,Asia,Credit Card

In [5]:
df.tail(2)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [6]:
df.loc[0][2]

/var/folders/xv/xj4pndmx0jlbqqr2xcl3wy280000gn/T/ipykernel_38081/2880214942.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][2]

'Electronics'

In [26]:
df = pd.read_csv('Sale_data.csv')
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [35]:
df.drop('Region', axis=1, inplace=True)

In [36]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,PayPal
...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Credit Card

In [37]:
df['Units Sold']=df['Units Sold']+1

In [38]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,3,999.99,1999.98,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,2,499.99,499.99,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,4,69.99,209.97,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,5,15.99,63.96,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,2,89.99,89.99,PayPal
...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,2,159.99,159.99,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,4,90.00,270.00,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,4,10.99,32.97,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,2,55.00,55.00,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,3,29.99,59.98,Credit Card

In [40]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    3.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    2.000000     6.500000       6.500000
25%       10060.75000    2.000000    29.500000      62.965000
50%       10120.50000    3.000000    89.990000     179.970000
75%       10180.25000    4.000000   249.990000     399.225000
max       10240.00000   11.000000  3899.990000    3899.990000